### ISSUE TITLE
你好，请问dokcer启动后，界面无法加载出来是啥问题

### ISSUE THREAD

**Issue by cfy3133** [lihuacai168/Jmeter-Toolkit#9]
![image](https://github.com/lihuacai168/Jmeter-Toolkit/assets/43978367/e6a7aa3a-5bb9-4800-ad5d-d0c58def5b9a)

**Comment by lihuacai168** [comment]
docker ps -a看一下容器状态
再docker logs -f 容器名，看一下日志

**Comment by cfy3133** [comment]
你好，docker logs -f日志如下：
![image](https://github.com/lihuacai168/Jmeter-Toolkit/assets/43978367/230f2d39-514b-4aec-b212-6132917dfa25)

**Comment by lihuacai168** [comment]
> 你好，docker logs -f日志如下： ![image](https://user-images.githubusercontent.com/43978367/248525412-230f2d39-514b-4aec-b212-6132917dfa25.png) docker ps -a日志显示正常运行

/docs这个是OK的？另外看到你有8005和8006两个端口，实际上你启动了哪个

**Comment by lihuacai168** [comment]
> > 你好，docker logs -f日志如下： ![image](https://user-images.githubusercontent.com/43978367/248525412-230f2d39-514b-4aec-b212-6132917dfa25.png) docker ps -a日志显示正常运行
> 
> /docs这个是OK的？另外看到你有8005和8006两个端口，实际上你启动了哪个

页面加载不出来，看样子是CDN的js加载出错了

**Comment by cfy3133** [comment]
是的，就是CDN的js加载不可以了，我直接用网页访问js那些都访问不了的，现在docker仓库也被墙了，我都是用建木的仓库来pull了，这个会不会是CDN那边出问题了

**Comment by lihuacai168** [comment]
> 是的，就是CDN的js加载不可以了，我直接用网页访问js那些都访问不了的，现在docker仓库也被墙了，我都是用建木的仓库来pull了，这个会不会是CDN那边出问题了

挂一下代理试试

**Comment by cfy3133** [comment]
见鬼了，今天来有可以了，之前一直不可以，啥都没改
![image](https://github.com/lihuacai168/Jmeter-Toolkit/assets/43978367/2d5b5cb3-f16d-4fbf-83d3-3e48c5933ade)

**Comment by lihuacai168** [comment]
> 见鬼了，今天来有可以了，之前一直不可以，啥都没改 ![image](https://user-images.githubusercontent.com/43978367/249009567-2d5b5cb3-f16d-4fbf-83d3-3e48c5933ade.png)

大概率是网络问题
